# Copyright 2020 - Offen Authors <hioffen@posteo.de>
# SPDX-License-Identifier: Apache-2.0

FROM golang:1.15

RUN apt-get update \
  && apt-get install -y \
  gettext \
  sqlite \
  && rm -rf /var/lib/apt/lists/*

ENV GOPATH=/go
WORKDIR /offen
# this is used for hot-reloading applications on change
# configuration is found in the application directories
# themselves
RUN go get github.com/markbates/refresh
