# Copyright 2020 - Offen Authors <hioffen@posteo.de>
# SPDX-License-Identifier: Apache-2.0

FROM golang:1.19

RUN apt-get update \
  && apt-get install -y \
  gettext \
  sqlite3 \
  && rm -rf /var/lib/apt/lists/*

ENV GOCACHE /data/cache

WORKDIR /offen
# this is used for hot-reloading applications on change
# configuration is found in the application directories
# themselves
RUN go install github.com/markbates/refresh@latest
