#!/usr/bin/env node

/**
 * Copyright 2020 - Offen Authors <hioffen@posteo.de>
 * SPDX-License-Identifier: Apache-2.0
 */

// This script expects to work against a `zones.tab` file as
// downloaded from https://www.iana.org/time-zones

var fs = require('fs')

const zoneFile = fs.readFileSync(process.argv[2])

var mapping = zoneFile.toString('utf8').split('\n')
  .filter(function (line) {
    return !/^#/.test(line)
  })
  .filter(Boolean)
  .reduce(function (acc, next) {
    var chunks = next.split('\t')
    acc[chunks[2].toUpperCase()] = chunks[0].toUpperCase()
    return acc
  }, {})

var asPojo = JSON.stringify(mapping, null, 2).replace(/"/g, '\'')
console.log('// This file is autogenerated. Do not edit.')
console.log('// Last updated: %s', new Date().toJSON())
console.log('module.exports =', asPojo)
